import * as yup from 'yup';

const cocktailSchema = yup.object().shape({
	idDrink: yup.string().required(),
	strDrink: yup.string().required(),
	strDrinkAlternate: yup.string().nullable(),
	strTags: yup.string().nullable(),
	strVideo: yup.string().url().nullable(),
	strCategory: yup.string().required(),
	strIBA: yup.string().nullable(),
	strAlcoholic: yup.string().required().oneOf(['Alcoholic', 'Non-Alcoholic']),
	strGlass: yup.string().required(),
	strInstructions: yup.string().nullable(),
	strInstructionsES: yup.string().nullable(),
	strInstructionsDE: yup.string().nullable(),
	strInstructionsFR: yup.string().nullable(),
	strInstructionsIT: yup.string().nullable(),
	"strInstructionsZH-HANS": yup.string().nullable(),
	"strInstructionsZH-HANT": yup.string().nullable(),
	strDrinkThumb: yup.string().url().nullable(),
	strIngredient1: yup.string().nullable(),
	strIngredient2: yup.string().nullable(),
	strIngredient3: yup.string().nullable(),
	strIngredient4: yup.string().nullable(),
	strIngredient5: yup.string().nullable(),
	strIngredient6: yup.string().nullable(),
	strIngredient7: yup.string().nullable(),
	strIngredient8: yup.string().nullable(),
	strIngredient9: yup.string().nullable(),
	strIngredient10: yup.string().nullable(),
	strIngredient11: yup.string().nullable(),
	strIngredient12: yup.string().nullable(),
	strIngredient13: yup.string().nullable(),
	strIngredient14: yup.string().nullable(),
	strIngredient15: yup.string().nullable(),
	strMeasure1: yup.string().nullable(),
	strMeasure2: yup.string().nullable(),
	strMeasure3: yup.string().nullable(),
	strMeasure4: yup.string().nullable(),
	strMeasure5: yup.string().nullable(),
	strMeasure6: yup.string().nullable(),
	strMeasure7: yup.string().nullable(),
	strMeasure8: yup.string().nullable(),
	strMeasure9: yup.string().nullable(),
	strMeasure10: yup.string().nullable(),
	strMeasure11: yup.string().nullable(),
	strMeasure12: yup.string().nullable(),
	strMeasure13: yup.string().nullable(),
	strMeasure14: yup.string().nullable(),
	strMeasure15: yup.string().nullable(),
	strImageSource: yup.string().url().nullable(),
	strImageAttribution: yup.string().nullable(),
	strCreativeCommonsConfirmed: yup.string().oneOf(['Yes', 'No']),
	dateModified: yup.string(),
	_deleted: yup.bool().default(false)
});

export default cocktailSchema;
